name: Docker CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: ["main", "develop"]
    types:
      - completed    

jobs:
  build-and-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          export DB_HOST= ${{ secrets.DB_HOST }}
          export DB_PORT= ${{ secrets.DB_PORT }}
          export DB_USER= ${{ secrets.DB_USER }}
          export DB_PASSWORD= ${{ secrets.DB_PASSWORD }}
          export DB_DATABASE= ${{ secrets.DB_DATABASE }}
          docker build -t usladelfino/api-restful-nodejs:latest .

      - name: Run tests
        run: docker run usladelfino/api-restful-nodejs:latest npm test