name: Docker Compose

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: ["main", "develop"]
    types:
      - completed

env:
  DOCKER_COMPOSE_VERSION: 1.29.2
  DOCKER_BUILDKIT: 1

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
        id: docker_login

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: usladelfino/api-restful-nodejs:latest
          builder: docker-compose
          builder-args: -f docker-compose.yml build app
          push-args: --ignore-undefined --compress
        env:
          DOCKER_BUILDKIT: ${{ env.DOCKER_BUILDKIT }}
          DOCKER_COMPOSE_VERSION: ${{ env.DOCKER_COMPOSE_VERSION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: Run tests
        run: docker run usladelfino/api-restful-nodejs:latest npm test