name: Docker CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: ["main", "develop"]
    types:
      - completed    

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  
jobs:
  build-and-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t usladelfino/api-restful-nodejs:latest --build-arg DB_HOST=${{ env.DB_HOST }} --build-arg DB_PORT=${{ env.DB_PORT }} --build-arg DB_USER=${{ env.DB_USER }} --build-arg DB_PASSWORD=${{ env.DB_PASSWORD }} --build-arg DB_DATABASE=${{ env.DB_DATABASE }} .

      - name: Run tests
        run: docker run -e DB_HOST=${{ env.DB_HOST }} -e DB_PORT=${{ env.DB_PORT }} -e DB_USER=${{ env.DB_USER }} -e DB_PASSWORD=${{ env.DB_PASSWORD }} -e DB_DATABASE=${{ env.DB_DATABASE }} usladelfino/api-restful-nodejs:latest npm test
        