name: JSDoc

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: ["main", "develop"]
    types:
      - completed   

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install JSDoc
        run: npm install -g jsdoc
      - name: Generate documentation
        run: npm run docs
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
