name: Gerar Documentação com JSDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Generate Documentation with JSDoc
        run: npx jsdoc -c jsdoc.json
      - name: Commit Documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Update documentation"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: .
          force: true
